const $ = (id) => document.getElementById(id);
const app = $('app');
const nav = $('nav');
const storeKey = 'portesLogiquesPlusV1';
const views = [
  ['inici','Inici'],['portes','Portes'],['taules','Taules'],['expressions','Expressions'],['circuits','Circuits'],['practica','Pràctica'],['docent','Docent'],['historial','Historial'],['ajuda','Ajuda']
];
const GATES = {
  AND:{label:'AND',inputs:2,symbol:'·',expr:'A · B',desc:'La sortida és 1 només si totes les entrades són 1.',fn:v=>v.every(Boolean)},
  OR:{label:'OR',inputs:2,symbol:'+',expr:'A + B',desc:'La sortida és 1 si almenys una entrada és 1.',fn:v=>v.some(Boolean)},
  NOT:{label:'NOT',inputs:1,symbol:'¬',expr:'¬A',desc:'Inverteix el valor de l’entrada.',fn:v=>!v[0]},
  NAND:{label:'NAND',inputs:2,symbol:'¬(·)',expr:'¬(A · B)',desc:'És la negació de l’AND.',fn:v=>!v.every(Boolean)},
  NOR:{label:'NOR',inputs:2,symbol:'¬(+)',expr:'¬(A + B)',desc:'És la negació de l’OR.',fn:v=>!v.some(Boolean)},
  XOR:{label:'XOR',inputs:2,symbol:'⊕',expr:'A ⊕ B',desc:'La sortida és 1 si les dues entrades són diferents.',fn:v=>v.filter(Boolean).length%2===1},
  XNOR:{label:'XNOR',inputs:2,symbol:'¬⊕',expr:'¬(A ⊕ B)',desc:'La sortida és 1 si les dues entrades són iguals.',fn:v=>v.filter(Boolean).length%2===0},
  MAJ3:{label:'Majoritària 3',inputs:3,symbol:'maj',expr:'AB + AC + BC',desc:'La sortida és 1 si com a mínim dues de tres entrades són 1.',fn:v=>v.filter(Boolean).length>=2}
};
const gateKeys = Object.keys(GATES);
let state = { view:'inici', gate:'AND', inputs:{A:0,B:0,C:0,D:0}, expr:'(A & B) | !C', practice:null };
function saveHistory(item){ const h=JSON.parse(localStorage.getItem(storeKey)||'[]'); h.unshift({...item,date:new Date().toLocaleString('ca-ES')}); localStorage.setItem(storeKey,JSON.stringify(h.slice(0,80))); }
function route(v){ state.view=v; render(); }
function renderNav(){ nav.innerHTML = views.map(([id,label])=>`<button class="${state.view===id?'active':''}" onclick="route('${id}')">${label}</button>`).join(''); }
function render(){ renderNav(); const fn = ({inici:renderInici,portes:renderPortes,taules:renderTaules,expressions:renderExpressions,circuits:renderCircuits,practica:renderPractica,docent:renderDocent,historial:renderHistorial,ajuda:renderAjuda})[state.view]; fn(); }
function gateSelect(id='gateSel'){return `<select id="${id}" onchange="state.gate=this.value; updateGateArea();"><option value="AND">AND</option><option value="OR">OR</option><option value="NOT">NOT</option><option value="NAND">NAND</option><option value="NOR">NOR</option><option value="XOR">XOR</option><option value="XNOR">XNOR</option><option value="MAJ3">Majoritària 3</option></select>`}
function setSelectValue(id,val){ const el=$(id); if(el) el.value=val; }
function combos(n){ const out=[]; for(let i=0;i<2**n;i++){ const row=[]; for(let b=n-1;b>=0;b--) row.push((i>>b)&1); out.push(row); } return out; }
function truthTable(gateKey){ const g=GATES[gateKey], labels=['A','B','C'].slice(0,g.inputs); return `<table class="truth"><thead><tr>${labels.map(x=>`<th>${x}</th>`).join('')}<th>Sortida ${g.label}</th></tr></thead><tbody>${combos(g.inputs).map(row=>{ const y=g.fn(row.map(Boolean))?1:0; return `<tr>${row.map(x=>`<td class="${x?'one':'zero'}">${x}</td>`).join('')}<td class="${y?'one':'zero'}">${y}</td></tr>`}).join('')}</tbody></table>`; }
function gateSvg(gateKey){ const g=GATES[gateKey]; const bubble = ['NOT','NAND','NOR','XNOR'].includes(gateKey); const label = gateKey==='MAJ3'?'MAJ':g.label; const in3 = g.inputs===3;
return `<svg width="270" height="150" viewBox="0 0 270 150" role="img" aria-label="Porta ${g.label}">
 <line x1="10" y1="${in3?40:55}" x2="80" y2="${in3?40:55}" stroke="#234f8f" stroke-width="4"/><text x="12" y="${in3?32:47}" fill="#234f8f" font-weight="700">A</text>
 ${g.inputs>1?`<line x1="10" y1="${in3?75:95}" x2="80" y2="${in3?75:95}" stroke="#234f8f" stroke-width="4"/><text x="12" y="${in3?67:87}" fill="#234f8f" font-weight="700">B</text>`:''}
 ${g.inputs>2?`<line x1="10" y1="110" x2="80" y2="110" stroke="#234f8f" stroke-width="4"/><text x="12" y="102" fill="#234f8f" font-weight="700">C</text>`:''}
 <rect x="80" y="25" width="105" height="100" rx="20" fill="#eaf2ff" stroke="#234f8f" stroke-width="4"/>
 <text x="132" y="84" text-anchor="middle" font-size="25" font-weight="800" fill="#234f8f">${label}</text>
 ${bubble?`<circle cx="197" cy="75" r="10" fill="white" stroke="#234f8f" stroke-width="4"/><line x1="207" y1="75" x2="255" y2="75" stroke="#234f8f" stroke-width="4"/>`:`<line x1="185" y1="75" x2="255" y2="75" stroke="#234f8f" stroke-width="4"/>`}
 <text x="245" y="64" fill="#234f8f" font-weight="700">S</text>
 </svg>`; }
function inputButtons(){ const g=GATES[state.gate], labels=['A','B','C'].slice(0,g.inputs); return labels.map(l=>`<div><strong>${l}</strong><br><button class="valuebtn ${state.inputs[l]?'on':''}" onclick="toggleInput('${l}')">${state.inputs[l]}</button></div>`).join(''); }
function toggleInput(k){ state.inputs[k]=state.inputs[k]?0:1; updateGateArea(); }
function calcGate(){ const g=GATES[state.gate]; const vals=['A','B','C'].slice(0,g.inputs).map(k=>!!state.inputs[k]); return g.fn(vals)?1:0; }
function updateGateArea(){ setSelectValue('gateSel',state.gate); const area=$('gateArea'); if(!area) return; const g=GATES[state.gate]; const y=calcGate(); area.innerHTML = `
 <div class="grid"><div class="card"><h3>${g.label}</h3><p>${g.desc}</p><p><span class="pill">Expressió: ${g.expr}</span></p><div class="svgbox">${gateSvg(state.gate)}</div></div>
 <div class="card"><h3>Càlcul d’una combinació</h3><div class="row">${inputButtons()}</div><p>Sortida:</p><div class="result">S = ${y}</div><div class="step">Amb ${['A','B','C'].slice(0,g.inputs).map(k=>`${k}=${state.inputs[k]}`).join(', ')}, la porta ${g.label} dona sortida <strong>${y}</strong>.</div><button class="btn secondary" onclick="copyText(gateSummary())">Copiar explicació</button> <button class="btn secondary" onclick="saveGate()">Guardar</button></div></div>
 <div class="card"><h3>Taula de veritat automàtica</h3><p class="muted">La taula es redibuixa sola quan canvies la porta.</p>${truthTable(state.gate)}</div>`; }
function gateSummary(){ const g=GATES[state.gate], y=calcGate(); return `Porta ${g.label}\nExpressió: ${g.expr}\nEntrades: ${['A','B','C'].slice(0,g.inputs).map(k=>`${k}=${state.inputs[k]}`).join(', ')}\nSortida: S=${y}`; }
function saveGate(){ saveHistory({type:'Porta lògica',title:`${GATES[state.gate].label}`,body:gateSummary()}); alert('Guardat a l’historial.'); }
function renderInici(){ app.innerHTML=`<div class="grid"><div class="card"><h2>Què permet fer?</h2><p>Aquesta PWA treballa portes lògiques de manera visual i pràctica. Serveix per a 1r i 2n de batxillerat, PAU, electrotècnia i sistemes digitals.</p><div class="row"><button class="btn" onclick="route('portes')">Començar amb portes</button><button class="btn secondary" onclick="route('practica')">Fer pràctica</button></div></div><div class="card"><h2>Flux recomanat</h2><div class="step">1. Tria una porta.</div><div class="step">2. Canvia les entrades 0/1.</div><div class="step">3. Mira la sortida i la taula.</div><div class="step">4. Passa a expressions o circuits.</div></div><div class="card"><h2>Inclou</h2><span class="pill">AND</span><span class="pill">OR</span><span class="pill">NOT</span><span class="pill">NAND</span><span class="pill">NOR</span><span class="pill">XOR</span><span class="pill">XNOR</span><span class="pill">Majoritària</span><span class="pill">Taules</span><span class="pill">Pràctica</span></div></div>`; }
function renderPortes(){ app.innerHTML=`<div class="card"><h2>Portes lògiques</h2><p>Tria la porta. La taula de veritat i el dibuix s’actualitzen automàticament.</p><div class="field"><label>Porta</label>${gateSelect()}</div></div><div id="gateArea"></div>`; updateGateArea(); }
function renderTaules(){ app.innerHTML=`<div class="card"><h2>Taules de veritat comparades</h2><p>Consulta les taules bàsiques de totes les portes.</p></div><div class="grid">${gateKeys.map(k=>`<div class="card"><h3>${GATES[k].label}</h3><div class="formula">${GATES[k].expr}</div>${truthTable(k)}</div>`).join('')}</div>`; }
function exprVars(expr){ return [...new Set((expr.toUpperCase().match(/[ABCD]/g)||[]))].sort(); }
function evalExpr(expr, vals){ let s=expr.toUpperCase().replace(/\s+/g,''); for(const [k,v] of Object.entries(vals)) s=s.replaceAll(k,v?'1':'0'); s=s.replace(/!/g,'!').replace(/¬/g,'!').replace(/\+/g,'||').replace(/\|/g,'||').replace(/·/g,'&&').replace(/&/g,'&&').replace(/⊕|\^/g,'!=='); if(!/^[01!()&|=\s]+$/.test(s)) throw new Error('Expressió no vàlida'); return Function(`return Number(Boolean(${s}))`)(); }
function expressionTable(expr){ const vars=exprVars(expr); if(!vars.length) return '<p>No hi ha variables A, B, C o D.</p>'; return `<table class="truth"><thead><tr>${vars.map(v=>`<th>${v}</th>`).join('')}<th>S</th></tr></thead><tbody>${combos(vars.length).map(row=>{ const vals={}; vars.forEach((v,i)=>vals[v]=!!row[i]); let y='?'; try{y=evalExpr(expr,vals)}catch(e){y='err'}; return `<tr>${row.map(x=>`<td class="${x?'one':'zero'}">${x}</td>`).join('')}<td class="${y===1?'one':'zero'}">${y}</td></tr>`; }).join('')}</tbody></table>`; }
function updateExpr(){ state.expr=$('exprInput').value; $('exprOut').innerHTML=expressionTable(state.expr); }
function renderExpressions(){ app.innerHTML=`<div class="grid"><div class="card"><h2>Expressions booleanes</h2><p>Escriu una expressió amb A, B, C, D. Operadors: <span class="kbd">&</span> AND, <span class="kbd">|</span> OR, <span class="kbd">!</span> NOT, <span class="kbd">^</span> XOR.</p><div class="field"><label>Expressió</label><input id="exprInput" value="${state.expr}" oninput="updateExpr()"></div><div class="row"><button class="btn secondary" onclick="setExpr('(A & B) | !C')">Exemple 1</button><button class="btn secondary" onclick="setExpr('(A ^ B) & C')">Exemple 2</button><button class="btn secondary" onclick="copyText($('exprOut').innerText)">Copiar taula</button></div></div><div class="card"><h2>Ajuda ràpida</h2><p><strong>Exemples:</strong></p><div class="formula">A & B<br>A | B<br>!A<br>(A & B) | C<br>A ^ B</div></div></div><div class="card"><h2>Taula generada</h2><div id="exprOut"></div></div>`; updateExpr(); }
function setExpr(e){ state.expr=e; $('exprInput').value=e; updateExpr(); }
function circuitEval(vals){ const g1=$('cg1')?.value||'AND', g2=$('cg2')?.value||'OR', g3=$('cg3')?.value||'AND'; const x=GATES[g1].fn([vals.A,vals.B]); const y=GATES[g2].fn([vals.C,vals.D]); const s=GATES[g3].fn([x,y]); return {x,y,s,g1,g2,g3}; }
function updateCircuit(){ const out=$('circOut'); if(!out) return; out.innerHTML=`<div class="svgbox"><svg width="520" height="230" viewBox="0 0 520 230"><text x="20" y="38" fill="#234f8f" font-weight="800">A</text><text x="20" y="75" fill="#234f8f" font-weight="800">B</text><text x="20" y="150" fill="#234f8f" font-weight="800">C</text><text x="20" y="187" fill="#234f8f" font-weight="800">D</text><line x1="40" y1="35" x2="120" y2="35" stroke="#234f8f" stroke-width="4"/><line x1="40" y1="72" x2="120" y2="72" stroke="#234f8f" stroke-width="4"/><rect x="120" y="20" width="105" height="70" rx="16" fill="#eaf2ff" stroke="#234f8f" stroke-width="4"/><text x="172" y="62" text-anchor="middle" font-weight="800" fill="#234f8f">${$('cg1').value}</text><line x1="40" y1="147" x2="120" y2="147" stroke="#234f8f" stroke-width="4"/><line x1="40" y1="184" x2="120" y2="184" stroke="#234f8f" stroke-width="4"/><rect x="120" y="132" width="105" height="70" rx="16" fill="#eaf2ff" stroke="#234f8f" stroke-width="4"/><text x="172" y="174" text-anchor="middle" font-weight="800" fill="#234f8f">${$('cg2').value}</text><line x1="225" y1="55" x2="310" y2="95" stroke="#234f8f" stroke-width="4"/><line x1="225" y1="167" x2="310" y2="135" stroke="#234f8f" stroke-width="4"/><rect x="310" y="80" width="105" height="70" rx="16" fill="#eaf2ff" stroke="#234f8f" stroke-width="4"/><text x="362" y="122" text-anchor="middle" font-weight="800" fill="#234f8f">${$('cg3').value}</text><line x1="415" y1="115" x2="500" y2="115" stroke="#234f8f" stroke-width="4"/><text x="480" y="103" fill="#234f8f" font-weight="800">S</text></svg></div>`+circuitTable(); }
function circuitTable(){ return `<table class="truth"><thead><tr><th>A</th><th>B</th><th>C</th><th>D</th><th>X</th><th>Y</th><th>S</th></tr></thead><tbody>${combos(4).map(r=>{const vals={A:!!r[0],B:!!r[1],C:!!r[2],D:!!r[3]}; const o=circuitEval(vals); return `<tr>${r.map(x=>`<td class="${x?'one':'zero'}">${x}</td>`).join('')}<td class="${o.x?'one':'zero'}">${+o.x}</td><td class="${o.y?'one':'zero'}">${+o.y}</td><td class="${o.s?'one':'zero'}">${+o.s}</td></tr>`}).join('')}</tbody></table>`; }
function renderCircuits(){ const opts=gateKeys.filter(k=>GATES[k].inputs===2).map(k=>`<option>${k}</option>`).join(''); app.innerHTML=`<div class="card"><h2>Constructor senzill de circuits</h2><p>Combina tres portes: la primera calcula X amb A i B, la segona calcula Y amb C i D, i la tercera combina X i Y.</p><div class="grid"><div class="field"><label>Porta 1: A,B → X</label><select id="cg1" onchange="updateCircuit()">${opts}</select></div><div class="field"><label>Porta 2: C,D → Y</label><select id="cg2" onchange="updateCircuit()">${opts}</select></div><div class="field"><label>Porta 3: X,Y → S</label><select id="cg3" onchange="updateCircuit()">${opts}</select></div></div></div><div class="card"><h2>Circuit i taula</h2><div id="circOut"></div></div>`; $('cg1').value='AND'; $('cg2').value='OR'; $('cg3').value='XOR'; updateCircuit(); }
const practiceBank=[
  {q:'Quina és la sortida d’una AND si A=1 i B=0?',a:'0',hint:'AND només dona 1 si totes són 1.'},
  {q:'Quina porta dona 1 si les entrades són diferents?',a:'XOR',hint:'És la porta exclusiva.'},
  {q:'Escriu la sortida de NOT amb A=0.',a:'1',hint:'NOT inverteix.'},
  {q:'En una OR amb A=0 i B=1, quina sortida hi ha?',a:'1',hint:'OR dona 1 si almenys una entrada és 1.'},
  {q:'Quina és la negació d’una AND?',a:'NAND',hint:'Nom de la porta AND negada.'}
];
function newPractice(){ state.practice=practiceBank[Math.floor(Math.random()*practiceBank.length)]; renderPractica(); }
function checkPractice(){ const ans=($('pracAns').value||'').trim().toUpperCase(); const ok=ans===state.practice.a.toUpperCase(); $('pracOut').innerHTML=`<div class="step" style="border-left-color:${ok?'var(--ok)':'var(--bad)'}"><strong>${ok?'Correcte':'Revisa-ho'}</strong><br>Resposta esperada: ${state.practice.a}<br>${state.practice.hint}</div>`; saveHistory({type:'Pràctica',title:state.practice.q,body:`Resposta: ${ans}. Esperada: ${state.practice.a}`}); }
function renderPractica(){ if(!state.practice) state.practice=practiceBank[0]; app.innerHTML=`<div class="grid"><div class="card"><h2>Pràctica autocorregible</h2><p><strong>${state.practice.q}</strong></p><div class="field"><label>Resposta</label><input id="pracAns" placeholder="Escriu la resposta"></div><div class="row"><button class="btn" onclick="checkPractice()">Comprovar</button><button class="btn secondary" onclick="$('pracOut').innerHTML='<div class=step>${state.practice.hint}</div>'">Pista</button><button class="btn secondary" onclick="newPractice()">Nou exercici</button></div><div id="pracOut"></div></div><div class="card"><h2>Mode docent</h2><p>Es pot projectar una pregunta, demanar que l’alumnat respongui en paper i després mostrar la pista o la solució.</p><button class="btn secondary" onclick="window.print()">Imprimir activitat</button></div></div>`; }
function renderDocent(){ app.innerHTML=`<div class="grid"><div class="card"><h2>Docent</h2><p>Genera una fitxa ràpida de classe.</p><div class="field"><label>Títol</label><input id="docTitle" value="Pràctica de portes lògiques"></div><div class="field"><label>Portes a treballar</label><textarea id="docGates">AND, OR, NOT, NAND, NOR, XOR</textarea></div><div class="field"><label>Objectiu</label><textarea id="docObj">Interpretar portes lògiques, completar taules de veritat i justificar la sortida.</textarea></div><button class="btn" onclick="makeDocSheet()">Generar fitxa</button></div><div class="card"><h2>Fitxa</h2><div id="docSheet" class="step">Encara no generada.</div></div></div>`; }
function makeDocSheet(){ $('docSheet').innerHTML=`<h3>${$('docTitle').value}</h3><p><strong>Portes:</strong> ${$('docGates').value}</p><p><strong>Objectiu:</strong> ${$('docObj').value}</p><ol><li>Tria una porta.</li><li>Completa la taula de veritat.</li><li>Dibuixa la porta.</li><li>Explica quan la sortida val 1.</li></ol><button class="btn secondary no-print" onclick="window.print()">Imprimir</button>`; }
function renderHistorial(){ const h=JSON.parse(localStorage.getItem(storeKey)||'[]'); app.innerHTML=`<div class="card"><h2>Historial</h2><div class="row"><button class="btn danger" onclick="localStorage.removeItem(storeKey);renderHistorial()">Esborrar historial</button></div></div>${h.length?`<div class="grid">${h.map((x,i)=>`<div class="card"><h3>${x.title}</h3><p class="muted">${x.type} · ${x.date}</p><pre class="formula">${x.body}</pre></div>`).join('')}</div>`:'<div class="card"><p>Encara no hi ha cap registre.</p></div>'}`; }
function renderAjuda(){ app.innerHTML=`<div class="card"><h2>Ajuda per començar</h2><div class="step"><strong>Portes:</strong> usa aquesta pestanya per veure una porta, canviar A/B/C i veure la taula automàtica.</div><div class="step"><strong>Taules:</strong> mostra totes les portes comparades.</div><div class="step"><strong>Expressions:</strong> permet escriure fórmules booleanes senzilles.</div><div class="step"><strong>Circuits:</strong> combina tres portes i genera la taula completa.</div><div class="step"><strong>Pràctica:</strong> preguntes autocorregibles.</div><p>Operadors d’expressions: <span class="kbd">&</span> AND, <span class="kbd">|</span> OR, <span class="kbd">!</span> NOT, <span class="kbd">^</span> XOR.</p></div>`; }
function copyText(t){ navigator.clipboard?.writeText(t); alert('Copiat.'); }
if('serviceWorker' in navigator){ navigator.serviceWorker.register('./sw.js').catch(()=>{}); }
window.route=route; window.state=state; window.updateGateArea=updateGateArea; window.toggleInput=toggleInput; window.copyText=copyText; window.gateSummary=gateSummary; window.saveGate=saveGate; window.updateExpr=updateExpr; window.setExpr=setExpr; window.updateCircuit=updateCircuit; window.newPractice=newPractice; window.checkPractice=checkPractice; window.makeDocSheet=makeDocSheet;
render();
